### ISSUE TITLE
multi chain and network config

### ISSUE THREAD

**Issue by xendarboh** [0KnowledgeNetwork/opt#2]
Short term: proxy requests to RPC providers
Longer term: run blockchain nodes for supported networks (and proxy for less popular chains/networks)

| chain | network | RPC Provider | Local RPC URL (example) |
| - | - | - | - |
| ethereum | mainnet | https://ethereum-rpc.publicnode.com | http://localhost:7070/ethereum |
| ethereum | sepolia | https://ethereum-sepolia-rpc.publicnode.com | http://localhost:7070/ethereum/sepolia |
| mina | mainnet | https://proxy.minaexplorer.com/graphql | http://localhost:7070/mina |
| mina | berkeley | https://proxy.berkeley.minaexplorer.com/graphql | http://localhost:7070/mina/berkeley |
| mina | devnet | https://proxy.devnet.minaexplorer.com/graphql | http://localhost:7070/mina/devnet |

and many many more over time...

Ideally: support multiple RPC Providers for a single network as fallbacks

Consider: Potential rate limits from RPC Providers when funneling requests from many clients. Some for-pay RPC providers offer more requests and performance within a "production" context.

**Comment by david415** [comment]
all these targets are in our config if i recall correctly.
