### ISSUE TITLE
upgrade walletshield to use client2

### ISSUE THREAD

**Issue by xendarboh** [0KnowledgeNetwork/opt#35]
Upgrade walletshield to use katzenpost client2 instead of the old client.

This upgrade should be project-wide to latest katzenpost supporting client2. Thus the http_proxy service plugin should also be confirmed working with the upgrade (automated tests should do this).

**Comment by amitbasuri** [comment]
Hi @david415 @xendarboh I would like to know if the PR https://github.com/0KnowledgeNetwork/opt/pull/36 is in the right direction.

**Comment by xendarboh** [comment]
Alright, the first thing I notice is that the git diff is far more noisy than expected. Please keep changes specific to this issue, for an effective review and smooth integration process. Only change behaviors necessary for migration to client2. (Other changes can be managed in separate issues and PRs).

These, mostly general, aspects are not in the desired direction:
- removal of test probe feature (don't remove features; they're used by other parts of the system)
- removal of error/log/help message usability improvements (don't downgrade the human experience)
- hard-coding of port listen address (don't remove or downgrade existing configuration abilities)
- change of output `Content-Type`; walletshield clients expect `application/json` as it is
